language: objective-c
osx_image: xcode9.2
gemfile: Gemfile

branches:
  only:
    - master

cache:
  - cocoapods

notifications:
  email:
   - muiz.idn@gmail.com

env:
  - ACTION=test DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=latest"

script:
  - xcodebuild -workspace EventClosure.xcworkspace -scheme EventClosure $ACTION -sdk iphonesimulator -destination $DESTINATION | xcpretty --color
